from ai_pr_review.models import AnalysisResult, Finding, Severity

SEVERITY_EMOJI = {
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
}

SEVERITY_LABEL = {
    Severity.HIGH: "高",
    Severity.MEDIUM: "中",
    Severity.LOW: "低",
}


def format_terminal(result: AnalysisResult) -> str:
    parts = []

    parts.append("📋 PR 变更总结")
    parts.append("━" * 40)
    parts.append(f"变更意图：{result.summary.intent}")
    parts.append(f"影响范围：{result.summary.scope}")
    parts.append("关键修改：")
    for change in result.summary.key_changes:
        parts.append(f"  - {change}")
    parts.append("")

    if result.findings:
        parts.append(f"⚠️  风险识别 ({len(result.findings)}项)")
        parts.append("━" * 40)
        for finding in result.findings:
            emoji = SEVERITY_EMOJI.get(finding.severity, "⚪")
            label = SEVERITY_LABEL.get(finding.severity, finding.severity.value)
            parts.append(
                f"{emoji} [{label}] {finding.file}:L{finding.line} - {finding.title} [{finding.expert}]"
            )
            parts.append(f"   {finding.description}")
            parts.append(f"   建议：{finding.suggestion}")
            if finding.code_snippet:
                parts.append(f"   代码：{finding.code_snippet}")
            parts.append("")

    if result.suggestions:
        parts.append(f"💡 Review 建议 ({len(result.suggestions)}项)")
        parts.append("━" * 40)
        for suggestion in result.suggestions:
            label = SEVERITY_LABEL.get(suggestion.priority, suggestion.priority.value)
            parts.append(f"  [{label}] [{suggestion.category}] {suggestion.description}")
            if suggestion.example:
                parts.append(f"   示例：{suggestion.example}")
            parts.append("")

    return "\n".join(parts)


def format_github_comment(result: AnalysisResult) -> str:
    parts = []

    parts.append("## 🤖 AI PR Review")
    parts.append("")
    parts.append("### 📋 变更总结")
    parts.append(f"**意图**：{result.summary.intent}")
    parts.append(f"**范围**：{result.summary.scope}")
    parts.append("**关键修改**：")
    for change in result.summary.key_changes:
        parts.append(f"- {change}")
    parts.append("")

    if result.findings:
        parts.append(f"### ⚠️ 风险识别 ({len(result.findings)}项)")
        parts.append("")
        for finding in result.findings:
            label = finding.severity.value.upper()
            parts.append(
                f"- **[{label}]** `{finding.file}:L{finding.line}` - {finding.title} _({finding.expert})_"
            )
            parts.append(f"  - {finding.description}")
            parts.append(f"  - 💡 建议：{finding.suggestion}")
            if finding.code_snippet:
                parts.append(f"  - 代码：`{finding.code_snippet}`")
        parts.append("")

    if result.suggestions:
        parts.append(f"### 💡 改进建议 ({len(result.suggestions)}项)")
        parts.append("")
        for suggestion in result.suggestions:
            parts.append(
                f"- **[{suggestion.priority.value.upper()}]** [{suggestion.category}] {suggestion.description}"
            )
            if suggestion.example:
                parts.append(f"  - 示例：`{suggestion.example}`")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by [AI PR Review](https://github.com/ai-pr-review)*")

    return "\n".join(parts)
